name: Code Quality

on: [push, pull_request]

jobs:
  qualitycheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy black isort ruff

    - name : Run ruff
      run: ruff check
    - name: Run black
      run: black --check .
    - name: Run isort
      run: isort --check --profile black .
    - name: Run mypy
      run: mypy --strict .
